### PR TITLE
Checkout partials

### PR DESCRIPTION
**Pull request by borcuttjahns**
All partials included - will need to discuss and recheck results (most params have dS/dParam = 0)

### CODE REVIEW

**Comment by aarmey** [comment]
@borcuttjahns are these plotted? I don't see them in Fig. 6.

Many should be 0. For example, all the rates involving other cytokines. Some of these we can eventually remove.

**Comment by borcuttjahns** [comment]
Alright I added the figure to the auto-build repertoire as S6 - and will integrate it with Zoe's figure (S5) once she finishes that up. What concerns me is that none of the reverse rates have an effect on specificity - if you get time to take a look I'd also like you're feedback on whether the results look as expected!

**Comment by aarmey** [comment]
@borcuttjahns agreed that the results look weird. In particular, I see that in these results aren't zero for some of the receptor expression rates for receptors of IL-4, etc, which aren't IL-2 and have no ligand expressed. Did they look more reasonable before the switch to 60 parameters? If so it might be something in the changes I made. E.g. runckineS might not be passing back the sensitivities in exactly the right shape, in which case everything would become jumbled.

**Comment by borcuttjahns** [comment]
For better or worse, these changes mirror exactly what results we were getting from the 30 parameter version. I'll merge this now and investigate today regarding what might be causing this.

**Pull request merged**
