### PR TITLE
Add ODEs

### PR DESCRIPTION
**Pull request by borcuttjahns**
Included the ODEs in markdown form in the methods section and referenced them in section one of the results. This should address a number of reviewer concerns - have double checked them but another eye wouldn't hurt, and let me know if the style/formatting is something you like!

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
A few initial changes:

- Let's make the label parts (fwd, rev) subscript. You can do this with an underscore (`k_{fwd}`, `k_{2,rev})
- The complex names should go in square brackets (e.g., `[IL2·IL2R]`).

We'll also need to make sure this doesn't run off the page, but first I'm going to reduce the font size.

**Comment by borcuttjahns** [comment]
Made the requested fixes. I'll start finishing up addressing reviewer comments - once that's done I think we should talk about formatting requirements.

**Review by aarmey — APPROVED** [review]
Ok, there's some additional formatting to eventually take care of, but let's merge this and finish up the response to reviewers.

**Comment by aarmey** [comment]
Getting the equations exactly right will take some more advanced Latex, and it's better for me to just do that. It's not worth your time to learn it for this one situation.

**Pull request merged**
