### PR TITLE
Easy edits

### PR DESCRIPTION
**Pull request by borcuttjahns**
Here are the responses for Reviewer 1's "easy" criticisms. There's a decent amount here so I thought I'd show you before I dive into more stuff simultaneously. The biggest change is to figure 1 - again I changed to Ka's here. Since that doesn't play well with numberings etc. I ended up thinking that we would leave references to the parameters in the text, and translate the "clearer" text in the figures to the actual rate constants in the captions. I think if we have the ODE's as supplemental material this is the clearest way to do this without losing specificity - definitely let me know what you think though, as it is a judgment call.

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
This all looks great! I think the only edit I see is in Fig. 1 with the Ka's. We should include the units of Ka there, especially because I think it's different than usual.

**Comment by borcuttjahns** [comment]
Added in Ka units to caption of Fig 1.

**Comment by borcuttjahns** [comment]
I have to admit I can't find the source of the testing error. I've updated gcSolver and pulled all updates from master, and none of the updates here have anything to do with the test that seems to be failing. Do you have a better intuition for what's going on here?

**Comment by aarmey** [comment]
We can ignore it. A random value just ended up a bit higher than the tolerance.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
