### PR TITLE
Mut scale

### PR DESCRIPTION
**Pull request by borcuttjahns**
This fixes the model mutein overlay for figures 6 and S7. I still need to fix a few subpanels on figure 6 but wanted to run this by you first. Also just to confirm, do we need to scale for the gonnord or ring predictions in figures 1 and 2? They look fine without scaling implemented since the model is fit to that data, but was unsure whether I should include that as another scaling effort.

### CODE REVIEW

**Comment by aarmey** [comment]
Figures 1 and 2 don't need scaling—they're handled separately.

**Comment by aarmey** [comment]
Could you remind me which thing you are scaling to? Are the replicates being scaled to the model in every case?

**Comment by aarmey** [comment]
I think I'm confused as to why the model confidence ranges have gotten so large...

**Comment by borcuttjahns** [comment]
So currently we're scaling experimental measures to predicted values. We're doing scaling separated by cell type and day on which signaling experiments were done. No signaling experiment was performed twice for a single mutein. 
The model predictions appearing to get more confident seems strange to me as I'm not currently touching them - I'm not sure if the previous sigmoidal scaling would have been affecting that in any way without diving in deeper.

**Comment by aarmey** [comment]
Nvm. I was misremembering something. This looks good so I'll merge it right after this comment. The results look very promising.

I think the next thing to figure out is the baseline. For example, the lowest concentration is sometimes far off from 0. One possibility is to just remove the intercept term in the scaling. In that case we can solve for the scaling using `lstsq`:

https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html

Another possibility is that it's occurring because the data within an experiment isn't on a consistent baseline. If this is the case then removing the offset won't help, and we need to do some raw data correction.

It's probably helpful to look at why N88 is so far off to determine what we need to fix. Is it offset from 0 because of the scaling intercept term, or because the raw data isn't on a consistent baseline with the other cytokines run on that day?

**Comment by aarmey** [comment]
P.S. The y-axis for a given cell type should be the same across all the plots in Fig. S7.

**Pull request merged**
