### PR TITLE
Remove scale

### PR DESCRIPTION
**Pull request by aarmey**

### CODE REVIEW

**Comment by aarmey** [comment]
@borcuttjahns I'm not sure that the Figs. 6 and S7 scalings are consistent? For example, look at the model-data comparison in each of these for WT C-term:

Screen Shot 2020-11-03 at 6 19 05 AM

Screen Shot 2020-11-03 at 6 20 29 AM

**Comment by borcuttjahns** [comment]
I fixed the ordering issue with the last PR - some DF ordering was at fault, but we should be good to go.

**Comment by aarmey** [comment]
@borcuttjahns I'm ready to merge this. Any hesitations in doing so? There are still some things to work on, but I'll post those on Slack.

**Comment by borcuttjahns** [comment]
Looks good to me! I'll work on those requested changes after it's in.

**Pull request merged**
