### PR TITLE
Fixed Plots

### PR DESCRIPTION
**Pull request by borcuttjahns**
Fixed the plotting issues mentioned in the manuscript comments. Will add some text edits to complement.

### CODE REVIEW

**Comment by borcuttjahns** [comment]
I need to rethink Figure 6c actually. I believe I was thinking about derivatives with respect to Ka wrong.

**Comment by borcuttjahns** [comment]
I think calculating the actual d(specificity)/d(Ka) would probably prove a bit more difficult and potentially unintuitive, so I just made the labels a more clear representation of reverse binding rates. Should be good to go now.

**Review by aarmey — CHANGES_REQUESTED** [review]
I don't see any x-axis labels on Fig. 6C?

**Comment by borcuttjahns** [comment]
Should be fixed now - was just an issue with how we split our label strings.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
